<?php

namespace Database\Seeders;

use App\Models\Setting;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now  = now();
        $data = [
            [
                'title'      => 'email_address',
                'value'      => '"sales@spagreen.net"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'phone',
                'value'      => '"+8801400620055"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_server',
                'value'      => '"smtp"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_server_address',
                'value'      => '"smtp.elasticemail.com"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_user_name',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_password',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_mail_port',
                'value'      => '"465"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_encryption_type',
                'value'      => '"ssl"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_mail_from_name',
                'value'      => '"SaleBot"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_from_address',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_signature',
                'value'      => '"<p>Thanks</p><p>SaleBot</p>"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_offline_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'offline_payment_instruction',
                'value'      => '"<p>Please deposit to our bank account at:<\/p><p><br><\/p><p>FIRST CENTURY BANK USA<\/p><p>Routing (ABA): 061120084<\/p><p>Account number: 4012444212194<\/p><p>Beneficiary name: Abdul Mannan<\/p><p>Bank address: 1731 N Elm St&nbsp; Commerce, GA 30529 USA<\/p><p>---<\/p><p><br><\/p><p>Standard Chatered Bank PLC, Bangladesh<\/p><p>SWIFT CODE: SCBLBDDX<\/p><p>Account number: 01742022601<\/p><p>Branch: Gulshan<\/p><p>Address: 67, Gulshan Avenue, Gulshan, Dhaka-1212<\/p><p>Beneficiary name: SpaGreen Creative<\/p><p><font color=\"#ce0000\">* Above is sample payment information, you can change it in your payment gateway setting page<\/font><\/p>"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'stripe_key',
                'value'      => '"pk_test_2ttZXh7jmC7V9JKQENaq7SVH"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'stripe_secret',
                'value'      => '"sk_test_2qDzEY6o64liVUfurzLosjbM"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_stripe_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'payment_method',
                'value'      => '"paypal"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paypal_client_id',
                'value'      => '"ARVXzUnLw-7OmHzIVqqUe_otKVpgoYhv1lFv1SG3OZpUF6cUhDmS-DPawzUsSImQm8ezKo7W0cX0yCjc"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paypal_client_secret',
                'value'      => '"EA8fXJIkp6xHHG9iJmDbiKkuGvaicoDSqI4TIvwRmGy8zdRcKx--3vV3SGNWfySBI_W3a_kNnhCnddRQ"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_sandbox_mode_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paddle_api_key',
                'value'      => '"3dacf9f5b8f8285caab1a7e0a181fec1756af9db9de6c6625a "',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paddle_client_token',
                'value'      => '"test_ee6ed044679e6efb75700af5ad5"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paddle_sandbox_mode_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paddle_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_razorpay_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'razorpay_key',
                'value'      => '"rzp_test_0TxiJynxZFTbwx"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'razorpay_secret',
                'value'      => '"3WTWGfrzVjwTcVMgzy8phSpJ"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cron_key',
                'value'      => '"'.uniqid().'"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'last_cron_run_at',
                'value'      => '"'.Carbon::now()->format('Y-m-d H:i:s').'"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'api_documentation_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_default_menu_link',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_title',
                'value'      => '"Hero Title"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_description',
                'value'      => '"Hero Description"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_main_action_btn_enable',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_main_action_btn_label',
                'value'      => '"Action"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'whatsApp_settings_video_url',
                'value'      => '"https://www.youtube.com/watch?v=ipRTUj4LjOo"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'telegram_settings_video_url',
                'value'      => '"https://www.youtube.com/watch?v=KD-inlsobbI"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Setting::insert($data);
    }
}
