<?php

use Carbon\Carbon;
use App\Models\Setting;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->id();
            $table->string('lang')->default('en');
            $table->string('title')->index()->nullable();
            $table->mediumText('value')->nullable();
            $table->tinyInteger('status')->default(1)->comment('0 inactive, 1 active');
            $table->timestamps();
        });
        // Remove any existing data to avoid duplicates
        DB::table('settings')->truncate();
        $now  = now();
        $data = [
            [
                'title'      => 'system_name',
                'value'      => '"SaleBot"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'company_name',
                'value'      => '"SpaGreen Creative"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'default_language',
                'value'      => '"en"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'default_currency',
                'value'      => '"USD"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'default_country',
                'value'      => '"19"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'phone_country_id',
                'value'      => '"19"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'themes',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'header_font',
                'value'      => '"jost"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'header_font_size',
                'value'      => '"28"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'body_font',
                'value'      => '"poppins"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'body_font_size',
                'value'      => '"14"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'primary_color',
                'value'      => '"#354ABF"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'secondary_color',
                'value'      => '"#333333"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'link_color',
                'value'      => '"#354ABF"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hover_color',
                'value'      => '"#333333"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'footer',
                'value'      => '"footer_one"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'newsletter_title',
                'value'      => '"Subscribe Now To Get Special Features!"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_newsletter',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'currency_symbol_format',
                'value'      => '"symbol_amount"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'decimal_separator',
                'value'      => '"."',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'no_of_decimals',
                'value'      => '"2"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'live_api_currency',
                'value'      => '"0"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'useful_link_title',
                'value'      => '"Useful Links"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'resource_link_title',
                'value'      => '"Resources"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'quick_link_title',
                'value'      => '"Quick Links"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_copyright',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'copyright_title',
                'value'      => '"Copyright @ 2024 All Rights Reserved to SpaGreen"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_useful_link',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_quick_link',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_main_action_btn_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'secondary_btn_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'version_code',
                'value'      => '"1.0.0"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'current_version',
                'value'      => '"100"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paginate',
                'value'      => '"10"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'title'      => 'theme_color',
                'value'      => '"default"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'disable_email_confirmation',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'disable_otp_verification',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'header_menu',
                'value'      => '"a:3:{i:0;a:2:{s:5:\"label\";s:4:\"Home\";s:3:\"url\";s:1:\"\/\";}i:1;a:2:{s:5:\"label\";s:5:\"Price\";s:3:\"url\";s:8:\"#pricing\";}i:2;a:2:{s:5:\"label\";s:8:\"Features\";s:3:\"url\";s:9:\"#features\";}}"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Setting::insert($data);
        $data = [
            [
                'title'      => 'email_address',
                'value'      => '"sales@spagreen.net"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'phone',
                'value'      => '"+8801400620055"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_server',
                'value'      => '"smtp"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_server_address',
                'value'      => '"smtp.elasticemail.com"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_user_name',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_password',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_mail_port',
                'value'      => '"465"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_encryption_type',
                'value'      => '"ssl"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'smtp_mail_from_name',
                'value'      => '"SaleBot"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_from_address',
                'value'      => '',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'mail_signature',
                'value'      => '"<p>Thanks</p><p>SaleBot</p>"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_offline_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'offline_payment_instruction',
                'value'      => '"<p>Please deposit to our bank account at:<\/p><p><br><\/p><p>FIRST CENTURY BANK USA<\/p><p>Routing (ABA): 061120084<\/p><p>Account number: 4012444212194<\/p><p>Beneficiary name: Abdul Mannan<\/p><p>Bank address: 1731 N Elm St&nbsp; Commerce, GA 30529 USA<\/p><p>---<\/p><p><br><\/p><p>Standard Chatered Bank PLC, Bangladesh<\/p><p>SWIFT CODE: SCBLBDDX<\/p><p>Account number: 01742022601<\/p><p>Branch: Gulshan<\/p><p>Address: 67, Gulshan Avenue, Gulshan, Dhaka-1212<\/p><p>Beneficiary name: SpaGreen Creative<\/p><p><font color=\"#ce0000\">* Above is sample payment information, you can change it in your payment gateway setting page<\/font><\/p>"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'stripe_key',
                'value'      => '"pk_test_2ttZXh7jmC7V9JKQENaq7SVH"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'stripe_secret',
                'value'      => '"sk_test_2qDzEY6o64liVUfurzLosjbM"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_stripe_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'payment_method',
                'value'      => '"paypal"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paypal_client_id',
                'value'      => '"ARVXzUnLw-7OmHzIVqqUe_otKVpgoYhv1lFv1SG3OZpUF6cUhDmS-DPawzUsSImQm8ezKo7W0cX0yCjc"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paypal_client_secret',
                'value'      => '"EA8fXJIkp6xHHG9iJmDbiKkuGvaicoDSqI4TIvwRmGy8zdRcKx--3vV3SGNWfySBI_W3a_kNnhCnddRQ"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_sandbox_mode_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paddle_api_key',
                'value'      => '"3dacf9f5b8f8285caab1a7e0a181fec1756af9db9de6c6625a "',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'paddle_client_token',
                'value'      => '"test_ee6ed044679e6efb75700af5ad5"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paddle_sandbox_mode_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paddle_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_paypal_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'is_razorpay_activated',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'razorpay_key',
                'value'      => '"rzp_test_0TxiJynxZFTbwx"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'razorpay_secret',
                'value'      => '"3WTWGfrzVjwTcVMgzy8phSpJ"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cron_key',
                'value'      => '"' . uniqid() . '"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'last_cron_run_at',
                'value'      => '"' . Carbon::now()->format('Y-m-d H:i:s') . '"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'api_documentation_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'show_default_menu_link',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_title',
                'value'      => '"Enhance Your WhatsApp & Telegram Marketing"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_description',
                'value'      => '"SaleBot, developed by SpaGreen Creative, is a WhatsApp and Telegram Marketing Software as a Service (SaaS) script available for purchase on the Codecanyon marketplace.Hero Description"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_main_action_btn_enable',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'hero_main_action_btn_label',
                'value'      => '"Try It Now"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'ai_title',
                'value'      => '"Test the AI Chat System"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'ai_description',
                'value'      => '"Scan the QR code or click on the button and it will open your whatsapp or telegram. Then start a chat with the bot."',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'ai_main_action_btn_label',
                'value'      => '"Get Started Now"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'ai_main_action_btn_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'contact_email',
                'value'      => '"sales@spagreen.net"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'contact_phone',
                'value'      => '"+8801400620055"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'high_lighted_text',
                'value'      => '"Empower your business with SaleBot, Contact with us"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_title',
                'value'      => '"Say hello to Whatsapp and Telegram Marketing"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_main_action_btn_label',
                'value'      => '"Get Started Now"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_main_action_btn_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_main_chat_btn_label',
                'value'      => '"Chat Us"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_main_chat_btn_url',
                'value'      => '"#"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'cta_enable',
                'value'      => '"1"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'footer_useful_link_menu',
                'value'      => '"a:5:{i:0;a:3:{s:5:\"label\";s:10:\"Price Plan\";s:3:\"url\";s:8:\"#pricing\";s:9:\"mega_menu\";N;}i:1;a:3:{s:5:\"label\";s:4:\"FAQs\";s:3:\"url\";s:4:\"#faq\";s:9:\"mega_menu\";N;}i:2;a:3:{s:5:\"label\";s:8:\"Features\";s:3:\"url\";s:9:\"#features\";s:9:\"mega_menu\";N;}i:3;a:3:{s:5:\"label\";s:5:\"Store\";s:3:\"url\";s:8:\"#stories\";s:9:\"mega_menu\";N;}i:4;a:3:{s:5:\"label\";s:12:\"Testimonials\";s:3:\"url\";s:13:\"#testimonials\";s:9:\"mega_menu\";N;}}"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title'      => 'footer_quick_link_menu',
                'value'      => '"a:4:{i:0;a:3:{s:5:\"label\";s:14:\"Privacy Policy\";s:3:\"url\";s:1:\"#\";s:9:\"mega_menu\";N;}i:1;a:3:{s:5:\"label\";s:18:\"Terms & Conditions\";s:3:\"url\";s:1:\"#\";s:9:\"mega_menu\";N;}i:2;a:3:{s:5:\"label\";s:9:\"Community\";s:3:\"url\";s:1:\"#\";s:9:\"mega_menu\";N;}i:3;a:3:{s:5:\"label\";s:7:\"Contact\";s:3:\"url\";s:1:\"#\";s:9:\"mega_menu\";N;}}"',
                'status'     => 1,
                'lang'       => 'en',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        Setting::insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('settings');
    }
};
